USE [master]
GO

/****** Object:  Database [SiparisYonetimi]    Script Date: 18.03.2022 17:42:57 ******/
CREATE DATABASE [SiparisYonetimi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SiparisYonetimi', FILENAME = N'C:\Users\ercan.ozturk\SiparisYonetimi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SiparisYonetimi_log', FILENAME = N'C:\Users\ercan.ozturk\SiparisYonetimi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SiparisYonetimi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SiparisYonetimi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET ARITHABORT OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SiparisYonetimi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SiparisYonetimi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SiparisYonetimi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SiparisYonetimi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SiparisYonetimi] SET  MULTI_USER 
GO

ALTER DATABASE [SiparisYonetimi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SiparisYonetimi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SiparisYonetimi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SiparisYonetimi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SiparisYonetimi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SiparisYonetimi] SET QUERY_STORE = OFF
GO

USE [SiparisYonetimi]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [SiparisYonetimi] SET  READ_WRITE 
GO


